### PR TITLE
Add support for SIGTSTP

### PR DESCRIPTION
**Pull request by jucor**
SIGTSTP is the signal received when the user sends Ctrl-Z from the
terminal. It is different from SIGSTOP, and was not yet supported by
lua-signal. This pull-requests adds it.

Example use:

``` lua
require 'signal'
require 'sys' -- for sleep

signal.signal('SIGTSTP', function() print('HELLO WORLD!') end)

while true do
    print('...')
    sys.sleep(1)
end
```

### CODE REVIEW

**Comment by batrick** [comment]
Thanks @jucor.

**Comment by jucor** [comment]
Thanks for the (quick!) merge @batrick! Do you know who would be in charge of updating the [luarocks rockspec](https://rocks.moonscript.org/modules/luarocks/lua_signal) to point to 1.2.1 instead of 1.2.0?

**Comment by batrick** [comment]
I believe Hisham manages the rockspec for lua-signal. Last time he told me about it, it sounded like it automatically checks for new tags. I would wait a few days to see if that happens. If it doesn't, let me know.

**Comment by jucor** [comment]
Sounds good, will do!

Julien Cornebise | Research Scientist | Google DeepMind | jucor@google.com

On Thu, Jul 24, 2014 at 10:02 PM, Patrick Donnelly <notifications@github.com

**Pull request merged**
